spring.application.name=Online_Shopping

# Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/Silver_Moon?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=P@ssword925
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate Configuration
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

# Specify the MySQL dialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql = true

# Set the maximum file size
spring.servlet.multipart.max-file-size=500MB

# Set the maximum request size
spring.servlet.multipart.max-request-size=500MB

# Spring Mvc Configuration
spring.mvc.static-path-pattern=/static/**
spring.web.resources.static-locations=classpath:/static/

# Thymeleaf Configuration
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp

# Detailed Logging
logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate=DEBUG
logging.level.com.dev.main=DEBUG
logging.file.name=logs/app.log

#Remember-me Configuration
security.rememberme.token-validity=1209600